---

- name: install tomcat package
  yum:
    name: tomcat
    state: latest
  become: true
  tags:
    - tomcat_install

- name: Enable tomcat to start on boot
  service:
    name: tomcat
    enabled: yes
    state: started
  become: true
    - tomcat_install

- name: create ansible tomcat directory
  file:
    path: /usr/share/tomcat/webapps/ROOT
    state: directory
  become: true
  tags:
    - tomcat_install
    - config_tomcat

- name: copy index.html to tomcat/webapps/ROOT/index.html
  template:
    src: root_index.html.j2
    dest: /usr/share/tomcat/webapps/ROOT/index.html
    mode: 0644
  become: true
  notify:
    - restart tomcat
  tags:
    - tomcat_install
    - config_tomcat