---

- name: install apache
  yum:
    name: httpd
    state: latest
  notify:
    - ensure apache started
  become: yes
  tags:
    - install_apache
    
- name: ensure apache enabled to start at boot
  service:
    name: httpd
    enabled: yes
  become: true