---
- import_playbook: deploy_common_play.yml
- import_playbook: deploy_postgres_to_db.yml
- import_playbook: deploy_tomcat-apache_to_apps.yml
- import_playbook: deploy_haproxy_to_frontends.yml
- import_playbook: smoketest_play.yml