---
- import_playbook: playbooks/deploy_common_play.yml
- import_playbook: playbooks/deploy_postgres_to_db.yml
- import_playbook: playbooks/deploy_tomcat-apache_to_apps.yml
- import_playbook: playbooks/deploy_haproxy_to_frontends.yml
- import_playbook: playbooks/smoketest_play.yml