---

- name: copy index.html to tomcat/webapps/ansible/index.html for each app server
  template:
    src: index.html.j2
    dest: /usr/share/tomcat/webapps/ansible/index.html
  become: yes
  notify:
    - restart tomcat