---

- name: Install httpie and haproxy
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - httpie
    - haproxy
  become: true

- name: Configure haproxy with template
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart HAproxy
  become: true