---

- name: Create path for tomcat file
  file:
    path: /usr/share/tomcat/webapps/ansible
    state: directory
    mode: 0755
  become: true
  tags:
    - tomcat_config

- name: copy index.html to tomcat/webapps/ansible/index.html for each app server
  template:
    src: ansible_index.html.j2
    dest: /usr/share/tomcat/webapps/ansible/index.html
  become: true
  notify:
    - restart tomcat
  tags:
    - tomcat_config