---

- name: install postgres
  yum:
    name: postgresql-server
    state: latest
  become: true
  notify: ensure postgres started

##only run the next 2 tasks once!
- name: initilize postgres
  command: postgresql-setup initdb
- name: initilize postgres some more
  command: chkconfig postgresql on