---

- name: install postgres
  yum:
    name: postgresql-server
    state: latest
  become: true
  notify: ensure postgres started

- name: Check if postgres has been init
  stat:
    path: /var/lib/pgsql/data/postgresql.conf
  register: postgress_init

- debug:
    var: postgress_init

- block:
  - name: initilize postgres
    command: postgresql-setup initdb
  - name: initilize postgres some more
    command: chkconfig postgresql on
  when: postgress_init is not defined
  tags:
    - sql_init